version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: normplov_django_api
    restart: always
    volumes:
      - .:/app
    ports:
      - "3290:8000"
    environment:
      - DEBUG=1
      - MONGO_DB_HOST=192.168.240.2
      - MONGO_DB_PORT=27017
      - MONGO_DB_NAME=normplov_istad_db
      - MONGO_DB_USER=lymannphy9
      - MONGO_DB_PASSWORD=hNxKDggpOVLXjLpd